services:
    _defaults:
       autowire: true
       autoconfigure: true
       public: false

    ## 安全裁切html
    phpdish_cms.html_chunker:
        class: PHPDish\CmsBundle\Utility\HtmlChunker
        arguments: ['@exercise_html_purifier.default']

    # 核心twig扩展
    phpdish_cms.twig_extension.core:
         class: PHPDish\Bundle\CmsBundle\Twig\CmsExtension
         tags: ['twig.extension']

    # 艾特处理解析器
    phpdish_cms.mention.parser:
        class: PHPDish\Component\Mention\MentionParser

    # body处理器
    phpdish_cms.body_processor:
        class: PHPDish\Bundle\CmsBundle\BodyProcessor\BodyProcessor
        arguments: ["@markdown.parser", "@phpdish_cms.mention.parser", "@exercise_html_purifier.default"]