services:
    phpdish_chat.message_provider:
        class: PHPDish\Bundle\ChatBundle\Message\Provider
        autowire: true
        parent: fos_message.provider

    PHPDish\Bundle\ChatBundle\Controller\:
         resource: "../../Controller"
         autowire: true
         arguments:
              $configuration: '@phpdish_resource.configuration.phpdish_chat'
         tags: ['controller.service_arguments']