services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    phpdish.chat.message_provider:
        class: PHPDish\Bundle\ChatBundle\Message\Provider
        parent: fos_message.provider

    PHPDish\Bundle\ChatBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish.resource.configuration.phpdish_chat'
         tags: ['controller.service_arguments']