easy_admin:
    site_name: 'PHPDish'
    formats:
        date:     'Y-m-d'
        time:     'H:i:s'
        datetime: 'Y-m-d H:i:s'

    design:
        brand_color: '#3c8dbc'
        color_scheme: 'dark'
        menu:
            - {entity: 'User', label: '用户', icon: 'users'}
            - {entity: 'Post', label: '文章', icon: 'bookmark', default: true }
            - {entity: 'Category', label: '专栏', icon: 'bookmark'}
            - {entity: 'Topic', label: '话题', icon: 'comment'}
            - {entity: 'Thread', label: '节点', icon: 'flag'}
            - {entity: 'FriendLink', label: '友情链接', icon: 'link'}
            - {entity: 'Wallet', label: '钱包', icon: 'credit-card'}
            - {entity: 'Payment', label: '交易', icon: 'credit-card'}

    entities:
        User:
            class: PHPDish\Bundle\UserBundle\Entity\User
            label: '用户'
            disabled_actions: ['new', 'delete']
            list:
                title: "%%entity_label%%列表"
                fields:
                    - id
                    - { property: 'avatar', type: 'image', label: '头像', base_path: '%app.path.avatar%'}
                    - { property: 'email', label: '邮箱', type:  'email' }
                    - { property: 'username', label: '用户名' }
                    - { property: 'lastLogin', label: '上次登录' }
                    - { property: 'enabled', label: '是否封禁',  type: 'toggle'}

            edit:
                title: "编辑%%entity_label%%"
                fields:
                    - { property: 'avatar', label: '头像', base_path: '%app.path.avatar%'}
                    - { property: 'email', label: '邮箱' }
                    - { property: 'username', label: '用户名' }
                    - { property: 'enabled', label: '是否封禁'}
                    - { property: 'plainPassword', label: '密码', type: 'text', type_options: { required: false } }
                    - { property: 'roles', label: '角色', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_SUPER_ADMIN': 'ROLE_SUPER_ADMIN' } } }



        Post:
            class: PHPDish\Bundle\PostBundle\Entity\Post
            label: '文章'
            disabled_actions: ['edit']
            list:
                title: "%%entity_label%%列表"
                fields:
                      - id
                      - { property: 'title', label: '标题' }
                      - { property: 'category', label: '所属专栏' }
                      - { property: 'user', label: '所属用户' }
                      - { property: 'recommended', label: '是否推荐', type: 'toggle' }
                      - { property: 'enabled', label: '状态',  type: 'toggle'}
                      - { property: 'comment_count', label: '评论数量' }
                      - { property: 'view_count', label: 'View数量' }
                      - { property: 'createdAt', label: '创建时间' }

        Category:
            class: PHPDish\Bundle\PostBundle\Entity\Category
            label: '专栏'
            disabled_actions: ['delete']
            list:
                title: "%%entity_label%%列表"
                fields:
                      - id
                      - { property: 'name', label: '专栏名称' }
                      - { property: 'slug', label: 'Slug' }
                      - { property: 'creator', label: '所属用户' }
                      - { property: 'cover', label: '封面', type: image, base_path: '%app.path.uploads%' }
                      - { property: 'recommended', label: '是否推荐', type: 'toggle' }
                      - { property: 'enabled', label: '是否删除',  type: 'toggle'}
                      - { property: 'description', label: '专栏简述' }
                      - { property: 'postCount', label: '文章数量' }
                      - { property: 'followerCount', label: '订阅数量' }
                      - { property: 'createdAt', label: '创建时间' }

            form:
                fields:
                      - { property: 'name', label: '专栏名称' }
                      - { property: 'slug', label: 'Slug' }
                      - { property: 'recommended', label: '是否推荐'}
                      - { property: 'enabled', label: '是否删除'}
                      - { property: 'description', label: '专栏简述' }
                      - { property: 'managers', label: '管理员' }
                      - { property: 'creator', label: '创建人' }


        Topic:
            class: PHPDish\Bundle\ForumBundle\Entity\Topic
            label: '话题'
            disabled_actions: ['edit', 'new']
            list:
                title: "%%entity_label%%列表"
                fields:
                      - id
                      - { property: 'title', label: '标题' }
#                      - { property: 'threads', label: '所属节点' }
                      - { property: 'recommended', label: '是否推荐', type: 'toggle' }
                      - { property: 'enabled', label: '状态',  type: 'toggle'}
                      - { property: 'replyCount', label: '回复数量' }
                      - { property: 'createdAt', label: '创建回复' }
                      - { property: 'repliedAt', label: '最后回复' }


        Thread:
            class: PHPDish\Bundle\ForumBundle\Entity\Thread
            label: '话题节点'
            disabled_actions: ['delete']
            list:
                title: "%%entity_label%%列表"
                fields:
                      - id
                      - { property: 'name', label: '名称' }
                      - { property: 'slug', label: 'Slug' }
                      - { property: 'enabled', label: '状态',  type: 'toggle'}
                      - { property: 'createdAt', label: '创建回复' }

            form:
                fields:
                      - { property: 'name', label: '名称' }
                      - { property: 'slug', label: 'Slug' }
                      - { property: 'description', label: '描述' }
                      - { property: 'enabled', label: '状态'}

        # 友情链接
        FriendLink:
            class: PHPDish\Bundle\WebBundle\Entity\FriendLink
            label: '友情链接'
            list:
                title: "%%entity_label%%列表"
                fields:
                      - { property: 'name', label: '名称' }
                      - { property: 'url', label: '链接', type: 'url'}
                      - { property: 'logo', label: 'Logo', type: 'image' }
                      - { property: 'priority', label: '优先级', type: 'number'}
            new:
                title: "新增%%entity_label%%"
            form:
                fields:
                      - { property: 'name', label: '名称' }
                      - { property: 'url', label: '链接', type: 'url'}
                      - { property: 'logo', label: 'Logo', type: 'url' }
                      - { property: 'priority', label: '优先级', type: 'number'}

        # 钱包
        Wallet:
            class: PHPDish\Bundle\PaymentBundle\Entity\Wallet
            label: '钱包'
            disabled_actions: ['edit', 'delete', 'new']
            list:
                title: "%%entity_label%%列表"
                actions: ['restock']
                fields:
                      - { property: 'user.username', label: '用户',}
                      - { property: 'id', label: 'ID' }
                      - { property: 'amount', label: '可用余额'}
                      - { property: 'freezeAmount', label: '冻结余额'}
                      - { property: 'createdAt', label: '创建时间'}
            search:
#                fields: ['user.username']

        # 钱包
        Payment:
            class: PHPDish\Bundle\PaymentBundle\Entity\Payment
            label: '交易历史'
            disabled_actions: ['edit', 'delete', 'new']
            list:
                title: "%%entity_label%%列表"
                fields:
                      - { property: 'user', label: '用户',}
                      - { property: 'wallet', label: '钱包',}
                      - { property: 'amount', label: '交易金额'}
                      - { property: 'type', label: '交易类型', template: 'PHPDishAdminBundle:Wallet:wallet_history_type.html.twig'}
                      - { property: 'status', label: '状态', template: 'PHPDishAdminBundle:Wallet:wallet_history_status.html.twig'}
                      - { property: 'description', label: '交易详情', type: 'raw'}
                      - { property: 'createdAt', label: '创建时间'}


# config/packages/sonata.yaml
sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
   title: 'PHPDish'
   title_logo: img/logo256.png
   dashboard:
       groups:
           phpdish.admin.group.user:
              label: 用户
              icon: '<i class="fa fa-user"></i>'

           phpdish.admin.group.post:
              label: 文章
              icon: '<i class="fa fa-file-text-o"></i>'

           phpdish.admin.group.forum:
              label: 话题
              icon: '<i class="fa fa-comment"></i>'

           phpdish.admin.group.wallet:
              label: 钱包
              icon: '<i class="fa fa-credit-card"></i>'

           phpdish.admin.group.site:
              label: 网站
              icon: '<i class="fa fa-laptop"></i>'