services:
    # 注册grid twig extension
    phpdish_admin.grid.twig_extension:
        class: PHPDish\Bundle\AdminBundle\Grid\Twig\GridExtension
        arguments: ['@twig', '%grid.base_template%']
        tags: ['twig.extension']