#easy_admin:
#    resource: "@EasyAdminBundle/Controller/"
#    type: annotation
#    prefix: /manager
#
#sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin
#
#sonata_admin_ex:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin

phpdish_admin:
    resource: "@PHPDishAdminBundle/Controller"
    prefix:   /admin
    type: annotation