services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    phpdish.manager.post:
        class: PHPDish\Bundle\PostBundle\Service\PostManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@markdown.parser'

    phpdish.manager.category:
        class: PHPDish\Bundle\PostBundle\Service\CategoryManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@phpdish.manager.payment'
            - '@router'
            - '@translator'

    phpdish.manager.book:
        class: PHPDish\Bundle\PostBundle\Service\BookManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@phpdish.manager.post'
            - '@phpdish.manager.category'

    phpdish.manager.post.comment:
        class: PHPDish\Bundle\PostBundle\Service\CommentManager
        public: true
        arguments:
            - ''
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - "@phpdish.body_processor"

    phpdish.form.type.post:
         class: PHPDish\Bundle\PostBundle\Form\Type\PostType
         arguments: ['@phpdish.manager.category']
         tags:
             - { name: form.type }

    phpdish.security.post_voter:
        class: PHPDish\Bundle\PostBundle\Security\PostVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false


    phpdish.security.comment_voter:
        class: PHPDish\Bundle\PostBundle\Security\CommentVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false

    phpdish.security.category_voter:
        class: PHPDish\Bundle\PostBundle\Security\CategoryVoter
        arguments: ['@security.access.decision_manager']
        tags:
             - { name: security.voter}
        public: false

    phpdish.avatar_generator.category:
        class: PHPDish\Bundle\ResourceBundle\AvatarGenerator\AvatarGenerator
        arguments: ['@phpdish.media.file_manager', '@phpdish.media.file_namer']

    phpdish.event_listener.category_persist:
        class: PHPDish\Bundle\PostBundle\EventListener\CategoryPersistListener
        arguments: ['@phpdish.avatar_generator.category']
        tags:
             - { name: kernel.event_listener, event: category.pre_persist, method: onCategoryPersist}
        public: false

    phpdish.event_listener.payment:
        class: PHPDish\Bundle\PostBundle\EventListener\PaymentListener
        arguments: ['@phpdish.manager.category', '@phpdish.manager.wallet']
        tags:
             - { name: kernel.event_listener, event: payment.paid, method: onPaymentPaid}
        public: false

    phpdish.twig_extension.post:
        class: PHPDish\Bundle\PostBundle\Twig\PostExtension
        public: false
        arguments:
            - "@phpdish.manager.category"
            - "@phpdish.manager.post"
            - "@phpdish.manager.post.comment"
        tags:
            - {name: twig.extension}

    phpdish.doctrine.orm.entity_listener.post:
        class: PHPDish\Bundle\PostBundle\EventListener\PostListener
        public: false
        arguments: ['@phpdish.manager.post', '@phpdish.manager.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\PostBundle\Model\Post, event: postPersist, method: postPersist}

    PHPDish\Bundle\PostBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish.resource.configuration.phpdish_post'
         tags: ['controller.service_arguments']