PHPDish\Bundle\PostBundle\Model\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: [slug]
             message: category.slug.unique

    properties:
       name:
           - NotBlank:
               message: category.name.not_blank
           - Length:
               min: 2
               max: 50
               minMessage: category.name.min_length
               maxMessage: category.name.max_length

       slug:
           - NotBlank:
               message: category.slug.not_blank
           - Regex:
               pattern: /^[0-9A-z\-]+$/
               message: category.slug.regex

       description:
           - Length:
                 min: 5
                 max: 500
                 minMessage: category.description.min_length
                 maxMessage: category.description.max_length


PHPDish\Bundle\PostBundle\Model\Post:
    properties:
        title:
            - NotBlank:
                message: post.title.not_blank
            - Length:
                 min: 10
                 max: 150
                 minMessage: post.title.min_length
                 maxMessage: post.title.max_length
                 groups: ['post']
            - Length:
                 min: 2
                 max: 50
                 minMessage: post.title.min_length
                 maxMessage: post.title.max_length
                 groups: ['chapter']

        originalBody:
            - NotBlank:
                 message:  post.original_body.not_blank
                 groups: ['post']
            - Length:
                 min: 150
                 minMessage: post.original_body.min_length
                 groups: ['post']