# PHPDish Mention Adapter
services:
    phpdish.security.password_encoder.generic:
        class: PHPDish\Bundle\CoreBundle\Security\Core\Encoder\GenericPasswordEncoder
        arguments: ['%security.password_encoder_strength%']

    phpdish.theme.context.generic:
        class: PHPDish\Bundle\CoreBundle\Theme\Context\GenericThemeContext
        arguments: ['@sylius.repository.theme', '%theme.current_theme%']

    phpdish.http_client:
        class: GuzzleHttp\Client
        arguments: [{verify: false}]

    phpdish.pinyin_translator:
        class: Overtrue\Pinyin\Pinyin

    ## 搜索服务，如果需要其它服务可以自行替换
    phpdish.searcher:
        class: PHPDish\Bundle\CoreBundle\Search\Algolia\AlgoliaSearch
        public: true
        arguments:
            - "@search.index_manager"
            - "@doctrine.orm.entity_manager"

    # mention 适配器
    phpdish.mention.adapter:
        class: PHPDish\Bundle\UserBundle\Mention\Adapter
        arguments: ['@phpdish.manager.user', '@router']

    ## 默认null engine
    search.engine.null:
        class: Algolia\SearchBundle\Engine\NullEngine

    ## locale manager
    phpdish.locale_manager:
        class: PHPDish\Bundle\CoreBundle\Locale\LocaleManager
        arguments: ['%locales%']

    phpdish.locale.listener:
        class: PHPDish\Bundle\CoreBundle\EventListener\LocaleListener
        arguments: ['@phpdish.locale_manager']
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20}