services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # 订阅者和监听者
    phpdish.event_listener.pjax:
         class: PHPDish\Component\Pjax\EventListener\KernelResponseListener
         arguments: ['@phpdish.pjax.helper']
         public: false
         tags:
            - { name: kernel.event_listener, event: 'kernel.response', method: 'onKernelResponse'}

    phpdish.event_listener.core.kernel:
         class: PHPDish\Bundle\CoreBundle\EventListener\KernelExceptionListener
         arguments: ['@security.token_storage', '@security.authorization_checker', '@router']
         public: false
         tags:
            - { name: kernel.event_listener, event: 'kernel.exception', method: 'onKernelException', priority: 1}

    phpdish.locale.listener:
        class: PHPDish\Bundle\CoreBundle\EventListener\LocaleListener
        arguments: ['@phpdish.locale_manager']
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20}

    phpdish.event_subscriber.user:
        class: PHPDish\Bundle\CoreBundle\EventListener\UserSubscriber
        arguments:
            - '@fos_user.user_manager'
            - '@fos_message.composer'
            - '@fos_message.sender'
            - '@translator'
            - '%chat.sender%'
            - '%chat.register_message%'
        tags: ['kernel.event_subscriber']

    phpdish.doctrine.orm.entity_listener.topic:
        class: PHPDish\Bundle\CoreBundle\EventListener\TopicListener
        public: false
        arguments: ['@phpdish.manager.topic', '@phpdish.manager.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\CoreBundle\Model\Topic, event: postPersist, method: postPersist}

    PHPDish\Bundle\CoreBundle\EventListener\Notification\:
         resource: '../../../EventListener/Notification/*'