# 核心路由
phpdish_kernel:
    resource: '@PHPDishCoreBundle/Resources/config/routing.yml'

# 前台路由
phpdish_frontend:
    resource: '@PHPDishWebBundle/Resources/config/routing.yml'

# 后台路由
phpdish_secured:
    resource: '@PHPDishAdminBundle/Resources/config/routing.yml'