services:

    phpdish_theme.file_locator:
        class: PHPDish\Bundle\ThemeBundle\Templating\Loade\FileLocator
        parent: file_locator
        calls:
           - {method: setThemeManager, arguments: ['@phpdish_theme.theme_manager']}

    phpdish_theme.template_locator:
        class: PHPDish\Bundle\ThemeBundle\Templating\Loade\TemplateLocator
        parent: templating.locator
        calls:
           - {method: setThemeManager, arguments: ['@phpdish_theme.theme_manager']}
