services:
    # Uploads 目录操作
    phpdish_media.file_manager.private:
       class: PHPDish\Component\Media\Manager\FileManager
       arguments: ['']

    phpdish_media.file_namer.private:
       class: PHPDish\Component\Media\Namer\DatePathNamer
       arguments: ['']

    phpdish_media.url_builder.private:
       class: PHPDish\Component\Media\UrlBuilder\GeneralBuilder
       arguments: ['@liip_imagine.cache.manager', '']

    phpdish_media.file_factory.private:
        class: PHPDish\Component\Media\Manager\FileFactory
        arguments: ['']

    phpdish_media.file_uploader.private:
       class: PHPDish\Component\Media\Manager\FileUploader
       arguments: ['', '']

    phpdish_media.file_downloader.private:
       class: PHPDish\Component\Media\Manager\FileDownloader
       arguments: ['@phpdish_core.http_client', '', '']

    phpdish_media.twig_extension:
        class: PHPDish\Bundle\MediaBundle\Twig\MediaExtension
        arguments: ['@service_container', '%cdn.host%']
        tags: ['twig.extension']

    ## CDN 处理
    phpdish_media.imagine.resolver:
        class: PHPDish\Bundle\MediaBundle\Imagine\CDNResolver
        parent: liip_imagine.cache.resolver.prototype.web_path
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: phpdish_media.imagine_resolver }

    ## 给oneup uploader使用
    phpdish_media.oneup_file_namer.private:
       class: PHPDish\Bundle\MediaBundle\Oneup\Naming\GenericNamer
       arguments: ['']