services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # 全局资源注册处
    phpdish_resource.resource_registry:
        class: PHPDish\Bundle\ResourceBundle\Metadata\ResourceRegistry

    # 各bundle资源配置基础对象
    phpdish_resource.configuration:
        class: PHPDish\Bundle\ResourceBundle\Controller\ResourceConfiguration

    phpdish_resource.event_subscriber.orm_mapped_super_class:
         class: PHPDish\Bundle\ResourceBundle\EventListener\ORMMappedSuperClassSubscriber
         arguments: ['@phpdish_resource.resource_registry']
         tags: ['doctrine.event_subscriber']
