services:
    phpdish.payment_gateway.youzan:
        class: Slince\YouzanPay\YouzanPay
        public: true
        arguments:
            -
            - {httpClient: "@phpdish.http_client"}

    phpdish.manager.payment:
        class: PHPDish\Bundle\PaymentBundle\Service\PaymentManager
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher", "@phpdish.manager.wallet", "@phpdish.payment_gateway.youzan"]

    phpdish.manager.wallet:
        class: PHPDish\Bundle\PaymentBundle\Service\WalletManager
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher", "@router", "@phpdish.manager.user", "@translator"]

    phpdish.money_formatter:
        class: PHPDish\Bundle\PaymentBundle\Money\MoneyFormatter

    phpdish.twig.extension.money:
        class: PHPDish\Bundle\PaymentBundle\Twig\MoneyExtension
        arguments: ["@phpdish.money_formatter"]
        public: false
        tags:
            - { name: twig.extension}

    phpdish.twig.extension.wallet:
        class: PHPDish\Bundle\PaymentBundle\Twig\WalletExtension
        arguments: ["@translator"]
        public: false
        tags:
            - { name: twig.extension}