PHPDish\Bundle\ForumBundle\Entity\Thread:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: [slug]
             message: thread.slug.unique

    properties:
       name:
           - NotBlank:
               message: thread.name.not_blank
           - Length:
               min: 2
               max: 50
               minMessage: thread.name.min_length
               maxMessage: thread.name.max_length

       slug:
           - NotBlank:
               message: thread.slug.not_blank
           - Regex:
               pattern: /^[0-9A-z\-]+$/
               message: thread.slug.regex

       description:
           - Length:
                 max: 500
                 maxMessage: thread.description.max_length


PHPDish\Bundle\ForumBundle\Entity\Topic:
    properties:
        title:
            - NotBlank:
                message: topic.title.not_blank
            - Length:
                 min: 10
                 max: 150
                 minMessage: topic.title.min_length
                 maxMessage: topic.title.max_length

        originalBody:
            - NotBlank:
                 message: topic.original_body.not_blank
            - Length:
                 min: 10
                 minMessage: topic.original_body.min_length

        threads:
            - NotBlank:
                message: topic.threads.not_blank