services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    phpdish.manager.notification:
        class: PHPDish\Bundle\NotificationBundle\Service\NotificationManager
        public: true
        arguments: ['',  '@doctrine.orm.entity_manager', '@translator']

    # Twig Extension
    phpdish.twig_extension.notification:
       class: PHPDish\Bundle\NotificationBundle\Twig\NotificationExtension
       tags: ['twig.extension']

    PHPDish\Bundle\NotificationBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish.resource.configuration.phpdish_notification'
         tags: ['controller.service_arguments']