services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    phpdish_notification.manager.notification:
        class: PHPDish\Bundle\NotificationBundle\Service\NotificationManager
        public: true

    # Twig Extension
    phpdish_notification.twig_extension.notification:
       class: PHPDish\Bundle\NotificationBundle\Twig\NotificationExtension
       tags: ['twig.extension']

    PHPDish\Bundle\NotificationBundle\Controller\:
         resource: "../../Controller"
         arguments:
              $configuration: '@phpdish_resource.configuration.phpdish_notification'
         tags: ['controller.service_arguments']