services:
    phpdish_user.security.password_encoder.generic:
        class: PHPDish\Bundle\UserBundle\Security\Core\Encoder\GenericPasswordEncoder
        arguments: ['%security.password_encoder_strength%']

    phpdish_user.manager.user:
        class: PHPDish\Bundle\UserBundle\Service\UserManager
        parent: fos_user.user_manager
        calls:
             - [setEventDispatcher, [ '@event_dispatcher']]
             - [setTranslator, [ '@translator']]
        public: true

    phpdish_user.avatar_generator.user:
        class: PHPDish\Bundle\ResourceBundle\AvatarGenerator\AvatarGenerator
        arguments: ['@phpdish_media.file_manager.avatar', '@phpdish_media.file_namer.avatar']

    phpdish_user.event_subscriber.user_subscriber:
        class: PHPDish\Bundle\UserBundle\EventListener\UserSubscriber
        arguments: ['@event_dispatcher', '@router', '@phpdish_user.avatar_generator.user']
        tags:
            - {name: doctrine.orm.entity_listener, entity: PHPDish\Bundle\UserBundle\Model\User, event: postPersist,  method: postPersist}
            - {name: 'kernel.event_subscriber'}

    phpdish_user.oauth_aware.user_provider:
        class: PHPDish\Bundle\UserBundle\Security\Core\User\FOSUBUserProvider
        arguments:
          - '@fos_user.user_manager'
          - '@security.token_storage'
          - '@phpdish_media.file_downloader.avatar'
          - {weibo: weiboId, github: githubId, qq: qqId}

    # Form Type
    phpdish_user.form_type.user_profile:
        class: PHPDish\Bundle\UserBundle\Form\Type\ChangeUserProfileType
        arguments: ['@phpdish_core.locale_manager']
        autowire: true
        tags: [form.type]

    # Setting Menu
    phpdish_user.menu_builder.setting_menu:
        class: PHPDish\Bundle\UserBundle\Menu\SettingMenuBuilder
        arguments: ['@knp_menu.factory', '@event_dispatcher']
        tags:
           - { name: knp_menu.menu_builder, method: createMenu, alias: setting_menu}

    # 核心twig扩展
    phpdish_user.twig_extension.user:
         class: PHPDish\Bundle\UserBundle\Twig\UserExtension
         arguments: ['@phpdish_user.manager.user']
         public: false
         tags:
            - { name: twig.extension}

   # 积分管理服务
    phpdish_user.manager.point:
        class: PHPDish\Bundle\UserBundle\Service\PointManager
        autowire: true

   # 积分变动
    phpdish_user.event_subscriber.point_history:
        class: PHPDish\Bundle\UserBundle\EventListener\PointHistorySubscriber
        autowire: true
        tags: ['doctrine.event_subscriber']