PHPDish\Bundle\ForumBundle\Model\Reply:
    exclusion_policy: ALL
    xml_root_name: reply
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        body:
            expose: true
            type: string
            groups: [Default, Detailed]
        originalBody:
            expose: true
            type: string
            groups: [Default, Detailed]
        voteCount:
            expose: true
            type: integer
            groups: [Default, Detailed]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        user:
            expose: true
            type: PHPDish\Bundle\UserBundle\Model\User
            groups: [Detailed]
        topic:
            expose: true
            type: PHPDish\Bundle\ForumBundle\Model\Topic
            groups: [Detailed]
