services:
    phpdish.manager.friend_link:
        class: PHPDish\Bundle\WebBundle\Service\FriendLinkManager
        arguments: ['@doctrine.orm.entity_manager']
        public: true

    phpdish.twig_extension.friend_link:
         class: PHPDish\Bundle\WebBundle\Twig\FriendLinkExtension
         arguments: ['@phpdish.manager.friend_link']
         public: false
         tags:
            - { name: twig.extension}