services:
   # Main Menu
    phpdish.menu_builder.main_menu:
        class: PHPDish\Bundle\WebBundle\Menu\MainMenuBuilder
        arguments: ['@knp_menu.factory', '@event_dispatcher']
        tags:
           - { name: knp_menu.menu_builder, method: createMenu, alias: main_menu}